name: PEP8 and tests

on:
  push:
    paths:
      - '.github/workflows/python.yml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/python.yml'
      - '**.py'

jobs:
  test_py:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [pypy2, pypy3]
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pypy flake8 and test
      run: |
        make test_flake8 test_pytest test_doctest test_other
